### ISSUE TITLE
How to get character-level prediction ?

### ISSUE THREAD

**Issue by trungpham2606** [faustomorales/keras-ocr#84] opened 2020-05-25 01:42 UTC
@faustomorales 
Thank you for sharing such a great module.
But I wonder how to get character-level prediction instead of whole words ?
I tried to change some threshold parameters but it seems doesnt work.

**Comment by faustomorales** [comment] 2020-07-30 01:20
I don't think this is possible with the CRAFT text detector -- at least not in an obvious and reliable way. This is not a bug, so I'm closing this issue for now.

**Closed by faustomorales** 2020-07-30 01:20 UTC
