### ISSUE TITLE
Verifying sha256 error

### ISSUE THREAD

**Issue by Goutam-Kelam** [faustomorales/keras-ocr#124] opened 2020-09-13 07:20 UTC
I tried running Keras-ocr on Colab as well as on local machine.
Everytime `pipeline = keras_ocr.pipeline.Pipeline()` is called `AssertionError: Error occurred verifying sha256.` comes up.

**Comment by faustomorales** [comment] 2020-09-13 18:55
Duplicate of https://github.com/faustomorales/keras-ocr/issues/117

**Closed by faustomorales** 2020-09-13 18:55 UTC
