### ISSUE TITLE
How to define box parameter of "warpBox" function's argument box ?

### ISSUE THREAD

**Issue by somiljain7** [faustomorales/keras-ocr#108] opened 2020-08-13 08:45 UTC
hey!
I am trying to build my own dataset for custom fine-tuning. I saw that in issue #3  you mentioned that  "a dataset where each image file is cropped to just one line of text. If your dataset is not cropped but you have the bounding boxes, you can use it in conjunction with keras_ocr.tools.warpBox to get just the line of text from the image.". I want to know how to define box parameter (like how to define lines ) for an image to be cropped to one line of text.

thank you

**Comment by faustomorales** [comment] 2020-08-14 02:00
Hi there -- please see [this section of the docs](https://keras-ocr.readthedocs.io/en/latest/api.html#keras_ocr.tools.warpBox) which explains how the arguments are expected to be provided. It is a list of four points starting in the top left corner and moving clockwise. The following would be one example.

```
box = [(0, 0), (10, 0), (10, 10), (0, 10)]
```

Closing this issue as it is not a bug.

**Closed by faustomorales** 2020-08-14 02:00 UTC
