### ISSUE TITLE
Detect and recognize meter reading

### ISSUE THREAD

**Issue by ferrygun** [faustomorales/keras-ocr#104] opened 2020-08-03 11:50 UTC
Hi, First of all, Thank you for the great project!

I would like to use it to detect and recognize the electric meter reading, is it possible using this library ?

**Comment by faustomorales** [comment] 2020-08-16 16:28
Sure, that's probably a good use case, though you will probably benefit from fine-tuning the [detector](https://keras-ocr.readthedocs.io/en/latest/examples/fine_tuning_detector.html) and [recognizer](https://keras-ocr.readthedocs.io/en/latest/examples/fine_tuning_recognizer.html) on a custom dataset. Closing for now since this is not a bug.

**Closed by faustomorales** 2020-08-16 16:28 UTC
