### ISSUE TITLE
I got an error,who can help me

### ISSUE THREAD

**Issue by wangwangww** [faustomorales/keras-ocr#47] opened 2020-03-13 14:27 UTC
E:\Anaconda\python.exe E:/keras-ocr/keras_ocr_texst.py
Traceback (most recent call last):
  File "E:/keras-ocr/keras_ocr_texst.py", line 1, in <module>
    import keras_ocr
  File "E:\Anaconda\lib\site-packages\keras_ocr\__init__.py", line 1, in <module>
    from . import (detection, recognition, tools, data_generation, pipeline, evaluation, datasets,
  File "E:\Anaconda\lib\site-packages\keras_ocr\detection.py", line 31, in <module>
    from . import tools
  File "E:\Anaconda\lib\site-packages\keras_ocr\tools.py", line 14, in <module>
    from shapely import geometry
  File "E:\Anaconda\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "E:\Anaconda\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "E:\Anaconda\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "E:\Anaconda\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "E:\Anaconda\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

Process finished with exit code 1

windows10
tensorflow-cpu =2.0
python= 3.7

**Comment by faustomorales** [comment] 2020-03-13 14:40
This appears to be the same issue as https://github.com/faustomorales/keras-ocr/issues/31 (a problem with installing `shapely`). Please take a look there to see if the solution at the end of the thread helps resolve your issue.

**Comment by faustomorales** [comment] 2020-03-27 23:18
Closing this issue because it appears to have been previously resolved for other users and no feedback has been provided for some time. If the issue is unresolved, please comment back and we can re-open.

**Closed by faustomorales** 2020-03-27 23:18 UTC
