### ISSUE TITLE
keras_ocr with flask

### ISSUE THREAD

**Issue by martingaudio94** [faustomorales/keras-ocr#80] opened 2020-05-21 13:24 UTC
Hi, i tried to given the service of keras_ocr trought flask api rest with post method, but i haven't good results,because:

1 - if i call the model every time i need it in a function, i get a memory overflow (the variables in memory don't overlap i think) and the memory goes to %99 an then the fask o django server goes down.

################code example 1###################
paths={'path':' '}

def detectar(path):
    detector=keras_ocr.detection.Detector()
    recognizer=keras_ocr.recognition.Recognizer()
    img=cv2.imread(path)
    boxes=detector.detect([img])[0]
    predict=recognizer.recognize_from_boxes(image=img,boxes=boxes)
    preds=[x[0] for x in predict]
    return preds

class HelloWorld(Resource):
    
    

    def post(self,path):
        preds=detectar(request.form['path'])
        preds=' '.join([x for x in preds])
        return preds

api.add_resource(HelloWorld, '/<string:path>')

if __name__ == '__main__':
    app.run(debug=True)

######### end example 1 ####################

2 - if i call the models 1 time like global variables (normal variable out of any function or class) and i call  the detect and recognize_from_boxes methods of Detector and Recognizer class in the function of post method, i get a the error  "tensor it's not an element of this graph"

######## code example 2 ##########

app = Flask(__name__)
api = Api(app)

paths={'path':' '}

detector=keras_ocr.detection.Detector()
recognizer=keras_ocr.recognition.Recognizer()
def detectar(path,detector,recognizer):

    img=cv2.imread(path)
    boxes=detector.detect([img])[0]
    predict=recognizer.recognize_from_boxes(image=img,boxes=boxes)
    preds=[x for x in predict]
    return preds

class HelloWorld(Resource):
    
    

    def post(self,path):
        preds=detectar(request.form['path'],detector,recognizer)
        preds=' '.join([x[0] for x in preds])
        return preds#{'path':preds}

api.add_resource(HelloWorld, '/<string:path>')

if __name__ == '__main__':
    app.run(debug=True)

#######end example code 2 ##########

anyone have an a idea what can helpt me ?

since thank for your time.

**Comment by faustomorales** [comment] 2020-05-23 17:24
Hi Martin -- Thanks for raising this issue.

Your first approach involved reloading the model on every request, which probably requires more memory than is reasonable for your application and will also make your server very slow.

Your second approach involved trying to share the same model object across requests, which is the better approach. But, like most web servers, Flask is using separate threads to handle each request and your model is not available in those threads. You may wish to consider the approaches described in [this StackOverflow question](https://stackoverflow.com/questions/51127344/tensor-is-not-an-element-of-this-graph-deploying-keras-model).

That said, this is a problem related to sharing resources across requests in Flask and not a bug or feature request for `keras-ocr`, so I'm closing this issue for now. If you do find a bug `keras-ocr`, please reply back and we can re-open.

**Closed by faustomorales** 2020-05-23 17:24 UTC

**Comment by wadnaa** [comment] 2020-12-11 07:50
Thanks @faustomorales
 
class Model:
	def __init__(self):
		self.session = tf.compat.v1.Session()
		self.graph = tf.compat.v1.get_default_graph()
		with self.graph.as_default():
		    with self.session.as_default():
		        self.detector = keras_ocr.detection.Detector()

	def predict(self, image):
		with self.graph.as_default():
		    with self.session.as_default():
		        boxes = self.detector.detect(images=[image])[0]
