### ISSUE TITLE
chinese text detection and recognition

### ISSUE THREAD

**Issue by simplew2011** [faustomorales/keras-ocr#95] opened 2020-06-24 10:59 UTC
Hi，thanks for your project.
Do you have any research on Chinese character detection and recognition?
Which is a more difficult scenario. 
If someone is training based on this code, is it possible to release the pre-trained model file to study.

**Comment by faustomorales** [comment] 2020-07-30 01:23
I don't have any trained models on Chinese characters, unfortunately. Closing this issue as it is not a bug.

**Closed by faustomorales** 2020-07-30 01:23 UTC
