### ISSUE TITLE
the train code release

### ISSUE THREAD

**Issue by simplew2011** [faustomorales/keras-ocr#100] opened 2020-07-16 07:50 UTC
would you release this train code.

**Comment by SungmanHong** [comment] 2020-07-27 05:36
me too

**Comment by faustomorales** [comment] 2020-07-30 01:12
Training code is available in the documentation.

https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html

**Comment by faustomorales** [comment] 2020-07-30 01:14
This is not a bug, so I'm closing this issue for now.

**Closed by faustomorales** 2020-07-30 01:14 UTC
