### ISSUE TITLE
Recognition part on ID card with rotation

### ISSUE THREAD

**Issue by bayethiernodiop** [faustomorales/keras-ocr#97] opened 2020-06-26 22:50 UTC
Hi, 
I am having problem with the OCR when the ID card image is rotated, the recognition is not finding text or it finds bad text.
Is there any nice way to handle this or doing the right rotation with the right angle before feeding the image to the OCR.
What do you think of this approach : https://d4nst.github.io/2017/01/12/image-orientation/ ?
Thanks

**Comment by faustomorales** [comment] 2020-07-30 01:27
Choosing the correct orientation for an image is out-of-scope for this package at this time but, if you find a suitable approach, a PR would be welcome for such functionality.

Closing this issue as it is not a bug.

**Closed by faustomorales** 2020-07-30 01:27 UTC
